name: mai-dev-environment

networks:
  database:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:16.3.0'
    networks:
      - database
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql-persistence:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=mai-db
      - POSTGRESQL_USERNAME=db_user
      - POSTGRESQL_PASSWORD=db_password
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./volumes/qdrant_storage:/qdrant/storage:rw

  traefik:
    # The official v3 Traefik docker image
    image: traefik:v3.1
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
    ports:
      # The HTTP port
      - '80:80'
      # The Web UI (enabled by --api.insecure=true)
      - '8080:8080'
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
