name: mai-dev-environment

networks:
  database:
    driver: bridge

services:
  postgresql:
    image: "bitnami/postgresql:16.3.0"
    networks:
      - database
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_DATABASE=mai-db
      - POSTGRESQL_USERNAME=db_user
      - POSTGRESQL_PASSWORD=db_password
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./volumes/qdrant_storage:/qdrant/storage:rw
